import type { ContentSnapshot } from "./types";
import type { ContentAdminSnapshot } from "./repository";

export const contentFixture: ContentSnapshot = {
  tagDefinitions: [
    { id: "000001", label: "pokenae" },
    { id: "000002", label: "ポケモン" },
    { id: "000003", label: "コレクション" },
    { id: "000004", label: "ツール" },
  ],
  banners: [
    { id: "welcome", image: "/mock/slide1.svg", alt: "pokenae ポケモン攻略ツール集", href: "/tools", order: 1, startsAt: "2026-01-01T00:00:00Z" },
    { id: "game-library", image: "/mock/slide2.svg", alt: "ゲームライブラリ Webアプリ", href: "/game-library", order: 2, startsAt: "2026-01-01T00:00:00Z" },
    { id: "blog", image: "/mock/slide3.svg", alt: "pokenae 技術ブログ", href: "/blog", order: 3, startsAt: "2026-01-01T00:00:00Z" },
  ],
  announcements: [
    { id: "site-renewal", text: "pokenae.com をリニューアルしました", href: "/blog/site-renewal", severity: "emphasis", startsAt: "2026-01-01T00:00:00Z" },
    { id: "github", text: "公開ツールとライブラリは GitHub でも配布しています", href: "https://github.com/p-o-ke-nae", severity: "normal", startsAt: "2026-01-01T00:00:00Z" },
  ],
  posts: [
    {
      slug: "site-renewal",
      title: "pokenae.com リニューアルのお知らせ",
      summary: "ツール、Webアプリ、ブログを探しやすい新しいサイトへ移行しました。",
      publishedAt: "2026-09-26",
      status: "published",
      category: "お知らせ",
      tags: ["000001"],
      relatedTags: [],
      priority: 100,
      thumbnail: "/pokenaeLogo.png",
      showInPickup: true,
      body: "## 新しい pokenae.com\n\nツール配布、Webアプリ、技術記事を一つのサイトから利用できるようになりました。\n\n生の HTML や JavaScript は記事内で実行されません。",
    },
    {
      slug: "collection-dex",
      title: "第4世代 全国図鑑コレクション",
      summary: "収集状況を地方や状態で絞り込めるショーケースです。",
      publishedAt: "2026-09-25",
      status: "published",
      category: "showcase",
      tags: ["000002", "000003"],
      relatedTags: ["000004"],
      priority: 90,
      thumbnail: "/pokenaeLogo.png",
      showInPickup: true,
      embed: { component: "CollectionDex", data: "./collection-dex.json" },
      body: "## CollectionDex\n\n以下は許可済みの CollectionDex コンポーネントです。\n\n{{CollectionDex}}",
    },
  ],
  tools: [
    {
      slug: "blink-observer-tool",
      name: "BlinkObserverTool",
      summary: "映像の変化を認識して作業を支援する Windows アプリです。",
      repository: "p-o-ke-nae/BlinkObserverTool",
      kind: "windows-app",
      supportedOs: ["Windows 10 以降 (x64)"],
      releaseChannel: "stable",
      image: "/pokenaeLogo.png",
      showInPickup: true,
      priority: 100,
      tags: ["000002", "000004"],
    },
    {
      slug: "generic-recognition-workbench",
      name: "GenericRecognitionWorkbench",
      summary: "認識処理を組み立てるための開発者向け .NET ライブラリです。",
      repository: "p-o-ke-nae/GenericRecognitionWorkbench",
      kind: "library",
      packageUrl: "https://github.com/p-o-ke-nae/GenericRecognitionWorkbench/packages",
      image: "/pokenaeLogo.png",
      showInPickup: true,
      priority: 80,
      tags: ["000004"],
    },
  ],
  apps: [
    {
      slug: "game-library",
      name: "ゲームライブラリ",
      summary: "ゲーム、ハード、セーブデータを管理します。既存URLはそのまま利用できます。",
      href: "/game-library",
      image: "/pokenaeLogo.png",
      imageAlt: "",
      metaLabel: "Google アカウント対応",
      status: "published",
      order: 1,
      tags: ["000002", "000003"],
    },
  ],
  updates: [
    { id: "renewal", publishedAt: "2026-09-26T14:30:00+09:00", target: "navigation", summary: "サイト構成とデザインを刷新しました。", href: "/", skipInfo: false },
  ],
};

export const contentAdminFixture: ContentAdminSnapshot = {
  revision: "0000000000000000000000000000000000000000",
  tags: contentFixture.tagDefinitions,
  banners: [
    { id: "welcome", image: "/mock/slide1.svg", alt: "pokenae ポケモン攻略ツール集", href: "/tools", order: 1, startsAt: "2026-01-01T00:00:00Z", endsAt: null },
  ],
  announcements: [
    { id: "site-renewal", text: "pokenae.com をリニューアルしました", href: "/blog/site-renewal", variant: "emphasis", startsAt: "2026-01-01T00:00:00Z", endsAt: null },
  ],
  tools: [
    {
      slug: "blink-observer-tool",
      displayName: "BlinkObserverTool",
      summary: "映像の変化を認識して作業を支援する Windows アプリです。",
      repository: "p-o-ke-nae/BlinkObserverTool",
      kind: "windows-app",
      docs: { readme: "README.md", paths: ["docs/"] },
      release: { channel: "stable", manifestRequired: true, unsignedInstaller: true },
      supportedOs: ["Windows 10 以降 (x64)"],
      showInPickup: true,
      priority: 100,
      tags: ["000002", "000004"],
    },
  ],
  toolPaths: ["content/tools/blink-observer-tool.json"],
  paths: [],
  postSources: [],
  schemas: {
    home: JSON.stringify({
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "image", "alt", "href", "startsAt", "endsAt", "order"],
        properties: {
          id: { type: "string", pattern: "^[a-z0-9-]+$" },
          image: { type: "string" },
          alt: { type: "string", minLength: 1 },
          href: { type: "string" },
          startsAt: { type: "string", format: "date-time" },
          endsAt: { type: ["string", "null"], format: "date-time" },
          order: { type: "integer", minimum: 0 },
        },
      },
    }),
    tool: JSON.stringify({
      type: "object",
      additionalProperties: false,
      required: ["slug", "displayName", "summary", "kind", "repository", "docs", "release", "tags", "showInPickup", "priority"],
      properties: {
        slug: { type: "string", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$" },
        displayName: { type: "string", minLength: 1 },
        summary: { type: "string", minLength: 1 },
        kind: { enum: ["windows-app", "library"] },
        repository: { type: "string", pattern: "^p-o-ke-nae/[A-Za-z0-9._-]+$" },
        docs: {
          type: "object",
          additionalProperties: false,
          required: ["readme", "paths"],
          properties: {
            readme: { type: "string" },
            paths: { type: "array", uniqueItems: true, items: { type: "string" } },
          },
        },
        release: {
          type: "object",
          additionalProperties: false,
          required: ["channel", "manifestRequired"],
          properties: {
            channel: { enum: ["stable"] },
            manifestRequired: { type: "boolean" },
            package: { type: "string" },
            unsignedInstaller: { type: "boolean" },
          },
        },
        supportedOs: { type: "array", uniqueItems: true, items: { type: "string" } },
        tags: { type: "array", uniqueItems: true, items: { type: "string", pattern: "^(?!000000)\\d{6}$" } },
        showInPickup: { type: "boolean" },
        priority: { type: "integer", minimum: 0, maximum: 1000 },
      },
    }),
    update: JSON.stringify({
      type: "object",
      additionalProperties: false,
      required: ["id", "publishedAt", "target", "summary", "href", "visible"],
      properties: {
        id: { type: "string", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$" },
        publishedAt: { type: "string", format: "date-time" },
        target: { enum: ["post", "tool", "app", "home", "navigation"] },
        summary: { type: "string", minLength: 1, maxLength: 200 },
        href: { type: "string" },
        visible: { type: "boolean" },
      },
    }),
  },
};
