import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/organisms/NavigationBar";
import SessionProvider from "@/components/organisms/SessionProvider";
import Footer from "@/components/organisms/Footer";
import TrialImportDialog from "@/components/molecules/TrialImportDialog";
import { LoadingOverlayProvider } from "@/contexts/LoadingOverlayContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <SessionProvider>
          <LoadingOverlayProvider>
            <NavigationBar />
            {children}
            <Footer />
            <TrialImportDialog />
          </LoadingOverlayProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
